### ISSUE TITLE
`window/workDoneProgress/cancel` is not according to spec

### ISSUE THREAD

**Issue by karthiknadig** [openlawlibrary/pygls#233] opened 2022-05-20 02:30 UTC
Looking at this:
https://github.com/openlawlibrary/pygls/blob/4772250f8ede25aee8e457dae5bca394aeccdd2f/pygls/progress.py#L62-L66

From the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_workDoneProgress_cancel) it looks like the `window/workDoneProgress/cancel` is a notification that comes from client, and not a request that is sent by the server.

**Comment by perrinjerome** [comment] 2022-07-17 12:58
> An API that would make sense to me would be `is_cancelled() -> bool` or `on_cancel(callback)`

I submitted a pull request ( #253 ) which implements this. The API is a future that is cancelled when `window/workDoneProgress/cancel` notification is received. If you have any feedback it would be appreciated, thanks.

**Comment by karthiknadig** [comment] 2022-07-18 18:08
@perrinjerome You changes look good, thanks for working on this.

**Comment by perrinjerome** [comment] 2022-07-18 21:39
Thank you @karthiknadig

**Comment by tombh** [comment] 2022-12-03 20:45
I'm just wondering how the new v1 release affects this issue? I think there are 2 problems identified here. Is the first one, that `window/workDoneProgress/cancel` is a client-to-server notification, fixed?

**Comment by perrinjerome** [comment] 2023-06-04 14:02
> Is the first one, that `window/workDoneProgress/cancel` is a client-to-server notification, fixed?

yes it's fixed in #253 as well, the problem is that this `cancel` method sends a notification to client from server, which does not make sense. In #253 the method is removed, which solves the problem.

( I'm sorry I did not notice this question earlier )

**Closed** 2023-06-04 14:21 UTC
